# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='adder.proto',
  package='adder',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61\x64\x64\x65r.proto\x12\x05\x61\x64\x64\x65r\"\"\n\nAddRequest\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\x1b\n\tAddResult\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\x35\n\x05\x41\x64\x64\x65r\x12,\n\x03\x61\x64\x64\x12\x11.adder.AddRequest\x1a\x10.adder.AddResult\"\x00\x42,\n\x16io.grpc.examples.adderB\nAdderProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='adder.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='adder.AddRequest.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='adder.AddRequest.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=56,
)


_ADDRESULT = _descriptor.Descriptor(
  name='AddResult',
  full_name='adder.AddResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='adder.AddResult.result', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['AddResult'] = _ADDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDREQUEST,
  __module__ = 'adder_pb2'
  # @@protoc_insertion_point(class_scope:adder.AddRequest)
  ))
_sym_db.RegisterMessage(AddRequest)

AddResult = _reflection.GeneratedProtocolMessageType('AddResult', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESULT,
  __module__ = 'adder_pb2'
  # @@protoc_insertion_point(class_scope:adder.AddResult)
  ))
_sym_db.RegisterMessage(AddResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026io.grpc.examples.adderB\nAdderProtoP\001\242\002\003HLW'))

_ADDER = _descriptor.ServiceDescriptor(
  name='Adder',
  full_name='adder.Adder',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=87,
  serialized_end=140,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='adder.Adder.add',
    index=0,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=_ADDRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDER)

DESCRIPTOR.services_by_name['Adder'] = _ADDER

# @@protoc_insertion_point(module_scope)
